Gym/Controllers/MembershipController.cs
using Gym.DTO;
using Gym.Interfaces;
using Gym.Models;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace Gym.Controllers
{
    public class MembershipController : Controller
    {
        private readonly IMembershipService _membershipService;

        public MembershipController(IMembershipService membershipService)
        {
            _membershipService = membershipService;
        }

        public IActionResult Memberships()
        {
            return View();
        }

        public async Task<IActionResult> DisplayMemberships()
        {
            var memberships = await _membershipService.DisplayMembershipAsync();

            return View(memberships);
        }

        public async Task<IActionResult> DisplayUserMemberships()
        {
            var user = User.FindFirst(ClaimTypes.NameIdentifier)?.Value;

            if (user == null)
            {
                return Unauthorized();
            }

            var getmembership = await _membershipService.DisplayUserMembershipAsync(user);

            return View(getmembership);
        }

        public async Task<IActionResult> DisplayEveryUserMemberships()
        {
            var getMemb = await _membershipService.DisplayEveryUserMembershipsAsync();

            return View(getMemb);
        }

        public IActionResult AddMemberships()
        {
            return View();
        }

        public async Task<IActionResult> AddMembershipsForm(AddMembershipDTO membership)
        {
            if (!ModelState.IsValid)
            {
                return View("AddMemberships", membership);
            }

            var newmembership = await _membershipService.AddMembershipAsync(membership);

            return RedirectToAction("DisplayMemberships");
        }

        public async Task<IActionResult> EditMemberships(int id)
        {
            var membershipForEdit = await _membershipService.GetMembershipForEditAsync(id);

            return View(membershipForEdit);
        }

        public async Task<IActionResult> EditMembershipsForm(UpdateMembershipDTO membershipToUpdate)
        {
            if (!ModelState.IsValid)
            {
                return View(membershipToUpdate);
            }

            await _membershipService.EditMembershipAsync(membershipToUpdate);

            return RedirectToAction("DisplayMemberships");
        }

        public async Task<IActionResult> BuyMembershipForm(int membershipId)
        {
            var user = User.FindFirst(ClaimTypes.NameIdentifier)?.Value;

            if (user != null)
            {
                await _membershipService.BuyMembershipAsync(membershipId, user);
            }

            return RedirectToAction("Memberships");
        }
    }

}

Gym/Controllers/RoleController.cs
using Gym.Interfaces;
using Gym.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Gym.Controllers
{
    [Authorize(Roles = "Admin")]
    public class RoleController : Controller
    {
        private readonly IRoleService _roleService;
        public RoleController(IRoleService roleService)
        {
            _roleService = roleService;
        }

        public IActionResult Roles()
        {
            return View();
        }

        public async Task<IActionResult> DisplayRoles()
        {
            var Roles = await _roleService.DisplayRoles();

            return View(Roles);
        }

        public IActionResult AssignRoles()
        {
            return View();
        }
        public async Task<IActionResult> AssignRolesForm(UserRole userRole)
        {
            if (!ModelState.IsValid)
            {
                return View("AssignRoles", userRole);
            }
            await _roleService.AssignRole(userRole.Email, userRole.Roles);

            return RedirectToAction("DisplayRoles");

            
        }
    }
}

Gym/Controllers/TrainerController.cs
using Gym.Data;
using Gym.DTO;
using Gym.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Gym.Controllers
{
    public class TrainerController : Controller
    {
        private readonly ITrainerService _trainerService;
        private readonly DataContext _context;
        
        public TrainerController(ITrainerService trainerService, DataContext context)
        {
            _trainerService = trainerService;
            context = _context;
            
        }

        public IActionResult Trainers()
        {
            return View();
        }

        public async Task<IActionResult> DisplayTrainers()
        {
            var trainers = await _trainerService.GetAllTrainersAsync();

            return View(trainers);
        }

       
        public async Task<IActionResult> AddTrainersForm(AddTrainerDTO trainer)
        {
            if (!ModelState.IsValid)
            {
                return View("AddTrainers",trainer);
            }

            if (trainer.Id == 0)
            {
                await _trainerService.AddTrainerAsync(trainer);
            }
           
           
           

            return RedirectToAction("DisplayTrainers");

            
        }

        public IActionResult AddTrainers()
        {
           
            return View();
        }

        public async Task<IActionResult> EditTrainers(int id)
        {
            var trainerForEdit =  await _trainerService.GetTrainerForEditAsync(id);

            return View(trainerForEdit);
        }

        public async Task<IActionResult> EditTrainersForm(UpdateTrainerDTO trainer) 
        {
            await _trainerService.EditTrainersAsync(trainer);
   
            return RedirectToAction("DisplayTrainers");

            
        }

        public async Task<IActionResult> DeleteTrainers(UpdateTrainerDTO trainer)
        {
            await _trainerService.DeleteTrainersAsync(trainer);

            return RedirectToAction("DisplayTrainers");
        }




    }
}

Gym/Controllers/TrainingController.cs
using Gym.DTO;
using Gym.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace Gym.Controllers
{
    public class TrainingController : Controller
    {
        private readonly ITrainingService _trainingService;

        public TrainingController(ITrainingService trainingService)
        {
            _trainingService = trainingService;
        }

        public IActionResult Trainings()
        {
            return View();
        }

        public async Task<IActionResult> DisplayTrainings()
        {
            var displayTraining = await _trainingService.DisplayTrainingsAsync();

            return View(displayTraining);
        }

        public async Task<IActionResult> AddTrainingsForm(AddTrainingDTO training)
        {
            if (!ModelState.IsValid)
            {
                return View("AddTrainings", training);
            }

            var newTraining = await _trainingService.AddTrainingAsync(training);
            
         
            return RedirectToAction("DisplayTrainings");
        }

        public IActionResult AddTrainings()
        {
            return View();
        }

        public async Task<IActionResult> DeleteTrainings(UpdateTrainingDTO training)
        {
            await _trainingService.DeleteTrainingAsync(training);

            return RedirectToAction("DisplayTrainings");
        }

        public async Task<IActionResult> EditTrainings(int id)
        {

            var training = await _trainingService.GetTrainingForEditAsync(id);

            return View(training);
        }

        public async Task<IActionResult> EditTrainingsForm(UpdateTrainingDTO training)
        {
            if (!ModelState.IsValid)
            {
                return View("EditTrainings", training);
            }
            await _trainingService.EditTrainingAsync(training);

            return RedirectToAction("DisplayTrainings");
        }
    }
}

Gym/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Gym</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Gym.styles.css" asp-append-version="true" />   
    <link rel="stylesheet" href="~/css/CustomStyles.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Gym</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @if (User.IsInRole("User") || User.IsInRole("Admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Trainer" asp-action="Trainers">Trainers</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Training" asp-action="Trainings">Trainings</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Membership" asp-action="Memberships">Membership</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Reservation" asp-action="Reservations">Reservation</a>
                            </li>
                        }
                       
                        @if (User.IsInRole("Admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Role" asp-action="Roles">Roles</a>
                            </li>
                        }
                        
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>

                    <partial name="_LoginPartial"></partial>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Gym - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)

</body>
</html>